### ISSUE TITLE
High view distances make the game unstable at high resolutions

### ISSUE THREAD

**Issue by ThatD07** [AeroWidescreen/NFSMW2012HDEffects#1]
In certain areas of the map, the game just crashes consistenly if World-, WaterReflection- and VehicleReflectionDistances are set too high (e.g. the maximum 15000.0)
One such spot is the McClane jackspot of the Agera R - if I select that spot and drive forward a bit, the game eventually crashes.

I'm playing on the Steam version (1.5.0.0)
This happens with both HD Effects 1.0.x and 2.0.0

Edit: In some cases, it even happens on default settings

**Comment by AeroWidescreen** [comment]
Can you share your INI file? What resolution are running the game in? I can't seem to reproduce this at all.

![agera](https://i.imgur.com/F6GHpHs.png)

For the record, I've had crashes that have forced me to axe features in development; different LOD improvements I wanted to do. It's probably running out of memory and I'm afraid the only solution is to set a stricter limit on view distance or even remove some features altogether. I'm hoping this won't be the case, but I'm not nearly as familiar with the Chameleon engine as I am with the "Speed" engine from Black Box to know how to increase memory pools.

**Comment by AeroWidescreen** [comment]
Okay, nevermind, I'm getting the same crash as well.

**Comment by ThatD07** [comment]
This is my ini file atm
[NFSMW2012HDEffects.txt](https://github.com/AeroWidescreen/NFSMW2012HDEffects/files/6524969/NFSMW2012HDEffects.txt)

I'm running the game at 1440p maxed, with super sampling disabled

Also another bug I just discovered
With HD Effects, the game doesn't seem to save the graphics settings when I change them
Usually, when I update the settings, Notepad++ tells me that the config file has been changed by another program, but with HD Effects, the config file doesn't get updated

**Comment by AeroWidescreen** [comment]
Thanks. Try this build and tell me if it stops crashing. Test the same area.
I found the game code that's at fault and I'm basically jumping over the code entirely. It's experimental, as I have no idea what the code was for (besides being LOD related), so please backup your save file as a precaution.

[Download](https://mega.nz/file/oTgUGbTK#n9oZyQEShNOQNOmd1HRKVa7q0lIShf0wO6C3tif4eoE)

> With HD Effects, the game doesn't seem to save the graphics settings when I change them

The build I posted should fix this as well.

**Comment by ThatD07** [comment]
> Thanks. Try this build and tell me if it stops crashing. Test the same area.
Unfortunately it still crashes for me. However, atleast the game does update the config file with this build.

**Comment by AeroWidescreen** [comment]
> However, atleast the game does update the config file with this build.

Nice. At least that should be taken care of now.

> Unfortunately it still crashes for me. 

The crashing is inconsistent for me, so it's very hard to tell if I fixed the problem or if I'm just getting really lucky. I spent about 30 minutes playing: completed races and ambushes, drove around the map, loaded the Koenigsegg jackspot numerous of times, restarted numerous of times, etc. etc. All settings maxed, zero crashes.

Sorry for all the testing, but this should be the last time.

[Download](https://mega.nz/file/1ToHWSZJ#UkfJa19OWvx4B3VPfy0CgS3AP6de73hcNS22c0kQcSo)

![Proof](https://i.imgur.com/GadrgNg.png)
![Proof](https://i.imgur.com/suF5uP5.png)

**Comment by ThatD07** [comment]
Sorry, still crashes for me. Gonna do a total reinstall, with all files deleted, and I will test different resolutions too.

**Comment by ThatD07** [comment]
So a clean reinstall didn't help, but reducing the resolution to 1080p did.

**Comment by AeroWidescreen** [comment]
Interesting, I play this game at 1080p... so, yeah. Do you think this could be a vanilla bug? Have you tried without HD Effects installed? I'll have to do more testing with resolution later.

**Comment by ThatD07** [comment]
I've been playing at 1440p for about a month now, never had a crash without HD Effects.

**Comment by AeroWidescreen** [comment]
I released an update for the other issue you reported. Unfortunately, I can't really do much about this instability at the moment. I recommend disabling `CinematicMode` and `ViewDistance` if you want to play at 1440p. You'll still benefit from the resolution increase and vegetation fix, but you shouldn't crash anymore.

**Comment by ThatD07** [comment]
Well recently I updated to Game Ready Driver 466.77. Either that or HD Effects 2.0.1, but it's working properly for me now on all resolutions, even 1440p.
Closing the issue :)

**Comment by ThatD07** [comment]
...or I just got lucky that time. Back to crashing, although it only happens at a few places - for example that Agera R Jackspot location no longer crashes, however I can still make the game crash near the Ripley's Points Jackspot of the ZR1 - if you go behind the gas station coming from the highway. 
Gonna go on with Aero's suggestions, let me know if I should reopen the issue.

If you wish, I can record those "unstable" places when I have the time.
